name: intro-data-analytics
channels:
  - conda-forge
dependencies:
  - python=3.10
  - altair
  - black
  - isort
  - numpy
  - pandas
  - pip
  - pytest
  - jupyterlab
  - scipy
  - scikit-learn
  - seaborn
  - sympy
  - pip:
      - watermark
      - nb_black