name: intro-data-analytics
channels:
  - conda-forge
dependencies:
  - python=3.10
  - altair
  - black
  - graph-tool
  - python-graphviz
  - isort
  - numpy
  - networkx
  - pandas
  - pip
  - pytest
  - jupyterlab
  - scipy
  - scikit-learn
  - seaborn
  - sympy
  - pip:
    - watermark
    - nb_black